import type { Metadata } from "next"
import { Oswald } from "next/font/google"
import "./globals.css"

const inter = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "MusicPlayer",
  description: "Generated by create next app",
  icons: {
    icon: "/music_icon.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${inter.className} relative min-h-screen bg-black overflow-x-hidden p-2`}
      >
        {children}
      </body>
    </html>
  )
}
